version: '3.8'
services:
  api-gateway-8080:
    container_name: api-gateway-8080
    build: ./api-gateway-8080  # build bằng Dockerfile
    # image:  # build bằng hub docker
    ports:
      - 8080:8080
    networks:
      - node-network

  notify-service:
    container_name: notify-service
    build: ./notify-service  
    networks:
      - node-network

  order-service:
    container_name: order-service
    build: ./order-service  
    environment:
      - DATABASE_URL=postgresql://postgres:1234@some-postgres:5432/db_amazon
      - REDIS_HOST=some-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=1234
      - REDIS_TTL=5000
    networks:
      - node-network

  shipping-service:
    container_name: shipping-service
    build: ./shipping-service  
    networks:
      - node-network
  
networks:
  node-network:
    external: true
      